### ISSUE TITLE
Potential support for ex-data / ex-info?

### ISSUE THREAD

**Issue by Olical** [circleci/rollcage#47]
It'd be awesome to see the data embedded in an exception in rollbar. In your experience, do you think that would be possible or does their API just not support that kind of extra metadata?

I'm happy to PR it in if you think it's doable at all!

**Comment by marcomorain** [comment]
Hi Oliver, the `ex-data` _does_ get sent to Rollbar:

https://github.com/circleci/rollcage/blob/dc0df3913272354b8d8010b712e2b199358facb3/src/circleci/rollcage/core.clj#L314

This function here grabs the ex-data from any exceptions in the cause chain and merges it into a single map. I might have added that in a more recent version than you are using. I should keep a changelog :)

Can you give the latest (`1.0.208`) a rattle and see if you get that data?

I also added support for sending the source-code to Rollbar, so you should see the line of code + the 3 lines on either side at each level in the callstack.

**Comment by marcomorain** [comment]
Here is an item that I have open in a tab with `ex-data`:

![image](https://user-images.githubusercontent.com/448001/70238858-0f59d200-1762-11ea-9387-59e292b0ca76.png)

and then in Rollbar:

![image](https://user-images.githubusercontent.com/448001/70238918-33b5ae80-1762-11ea-8bdc-5023a5f82cca.png)

**Comment by Olical** [comment]
Oh! Silly me, I should've noticed the lack of source too since I've seen that in some projects now. A large amount of repos means a desync in common deps like this, should've checked that first, my bad.

Thank you for the great features! Sorry to bother you with something I should've easily spotted.

**Comment by marcomorain** [comment]
It's no problem at all - I'm glad to see that the project is being used by more teams than just us :)
